- include/mujincontrollerclient/mujincontrollerclient.h
- src/handeyecalibrationtask.cpp
- src/mujincontrollerclient.cpp
Since WebResource::Get is general method, it should be templated, I think.
The point is GETCONTROLLERIMPL() is not exported to include (it is in src/common.h), so I made a private (could be protected?) wrapper function named GetWrap which calls API.
> Generalized WebResource::Get

- src/controllerclientimpl.cpp
- src/controllerclientimpl.h
Explicit login against mujin controller is not necessary since March 2016.
> Remove unnecessary django login requests.

- samples/mujinupgrade.cpp
- src/controllerclientimpl.cpp
tested
- save/restore backup automated gtest (as modifying UploadViaForm could break backup feature)
- upgrading with uploading
- upgrading without uploading
very sorry for mistesting.
also contains mujinupgrade Windows compilation fix.
> fix form upload

- src/controllerclientimpl.cpp
I found when I was performing a stress test and instobject deletion raised exception.
> avoid SIGSEGV when DELETE fails, where error message was written in uninitialized FILE*

- README.rst
We would need this when we feel it is hard to continue supporting VC100.
By the way, this link is already deprecated, which I changed as well:
> Updating the Windows Libraries
> ------------------------------
> `boost <http://www.boostpro.com/download/>`_ (any version >= 1.45 is fine).
> added guide to upgrade Visual C++ (to 2015 etc)

- src/common.h
- src/controllerclientimpl.cpp
- src/mujincontrollerclient.cpp
- 5 places in the code uses `MUJIN_ASSERT_*`
- 42 places in the code uses `BOOST_ASSERT`
- `RAPIDJSON_ASSERT` uses `BOOST_ASSERT`
Clean up `MUJIN_ASSERT_*` to avoid leaking the assert exception across libraries.
> Clean up MUJIN_ASSERT, everyone else is using BOOST_ASSERT.

- src/mujincontrollerclient.cpp
Currently AddGeometryFromRawSTL fails at SetGeometryFromRawSTL's part because geometry->geomtype is not initialized properly.
SetGeometryFromRawSTL's implementation was wrong during MUJIN_ASSERT period. AddGeometryFromRawSTL was also wrong and it seemed to be working well.
To catch the MUJIN_ASSERT period's bug, Client.TestObjectLinkGeometryModifyMeter has been added to testcontrollerclientcpp (it is passing in master but failing in older hash)
> Initialize return value of AddLink/AddGeometry. Fix AddGeometryFromRawSTL as well.

- src/controllerclientimpl.cpp
CallPost uses "content-type:application/json" and putting raw parameter in data is not ok. need to use query string.
> Fixed DeleteFileOnController webstack2

- src/common.h
- src/controllerclientimpl.cpp
Starting in 7.43.0 any-domain cookies will not be exported
cf https://curl.se/libcurl/c/cookie_interface.html
@ziyan (although I tested locally) could you confirm master does not work on debian bullseye?
> Set cookie domain

- src/controllerclientimpl.cpp
test script
```
//usr/bin/env true; tmpfile=$(mktemp); g++ -O2 -std=c++11 -xc++ -o $tmpfile $0 -Dutf16=$UTF16 -I $MUJIN_INSTALL_DIR/include -L $MUJIN_INSTALL_DIR/lib -lmujincontrollerclient0.44 && $tmpfile; rm $tmpfile; exit
#include <iostream>
#include <mujincontrollerclient/mujincontrollerclient.h>
int main(){
auto client = mujinclient::CreateControllerClient("mujin:mujin", "foobar");
std::vector<unsigned char> vdata;
#if(utf16)
client->DownloadFileFromController_UTF16(L"mujin:/foobar.xyz", vdata);
#else
client->DownloadFileFromController_UTF8("mujin:/foobar.xyz", vdata);
#endif
}
```
result
```
$ UTF16=0 ./clientcpptest.cpp
log4cxx: No appender could be found for logger (mujin.controllerclientcpp).
log4cxx: Please initialize the log4cxx system properly.
terminate called after throwing …
```
> _PrepareDestinationURI_UTF16 should not lock mutex, safe to assume it is already locked

- include/mujincontrollerclient/mujinjson.h
- src/binpickingtask.cpp
- src/binpickingtaskzmq.cpp
- src/mujinzmq.cpp
Due to the upgraded header zmq C++ header file applied to the bullseye branch recently, compiling this causes the compiler to belch out a ton of unnecessary warnings due to deprecation and the like.
This pull request aims to fix those issues.
> Silence ZMQ related warnings

- include/mujincontrollerclient/mujinjson.h
- src/binpickingtask.cpp
- src/binpickingtaskzmq.cpp
- src/mujinzmq.cpp
Reverts mujin/controllerclientcpp#97
I don't think this is ready
> Revert "Silence ZMQ related warnings"

- include/mujincontrollerclient/binpickingtask.h
- src/binpickingtask.cpp
This patch adds lines to clear memory allocated for previous contents before copying new contents. (`rapidjson::Document::CopyFrom()` does not deallocate memory implicitly.) It also properly clears a previous value of `graspModelInfo` when a value is not given in the parsing function.
> Fix: Memory leak from ResultGetBinpickingState::RegisterMinViableRegionInfo::graspModelInfo

- include/mujincontrollerclient/mujincontrollerclient.h
- src/binpickingtask.cpp
- src/mujincontrollerclient.cpp
This PR seeks to address the issue of the controller client user hitting an error when calling `mujinclient::utils::GetSensorData/GetSensorTransform` with the `sensorname` argument referring to a connected body camera of the robot referred to with the `bodyname` argument.
The primary change this MR makes is adding a section in `RobotResource::GetAttachedSensors` for gathering attached sensor pointers from the robot resource's connected bodies before merging them into the attached sensors array that the method later iterates on.
> Fetch attached sensors from connected bodies in `RobotResource::GetAttachedSensors`

- src/controllerclientimpl.cpp
otherwise _CallGet sets curl timeout to default of 5s
> pass timeout to _CallGet

- src/mujinzmq.cpp
It is similar to https://github.com/mujin/mujincontrollerclientpy/blob/master/python/mujincontrollerclient/zmqclient.py#L119
----
When new controllerclientcpp is used with old webstack and ExecuteGraphQueryZmq, timeout happens. It is ok. But the thing is, the client program cannot be shutdown properly:
```
(gdb) bt
#0  0x00007f760d220d2f in __GI___poll (fds=fds@entry=0x7ffff06ee9e8, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f75eeba8a9d in zmq::signaler_t::wait(int) (this=this@entry=0x3303d58, timeout_=-1) at /home/mujin/mujin/checkoutroot/libzmq/src/signaler.cpp:242
#2  0x00007f75eeb8e012 in zmq::mailbox_t::recv(zmq::command_t*, int) (this=this@entry=0x3303cf0, cmd_=cmd_@entry=0x7ffff06eea80, timeout_=timeout_@entry=-1)
at …
```
> set ZMQ_LINGER when closing REP/REQ sockets

- src/binpickingtask.cpp
cmath's std::isnan has to be imported.
Initially reported by @achuie.
> fix isnan compilation (in newer gcc)

- include/mujincontrollerclient/binpickingtask.h
- src/binpickingtask.cpp
- Structure that represent a point cloud 3D by its 3D position and it orientation axes. 
- A list of point cloud 3D corners into ObjectInfo.
- Respective json parsing
[//]: # (If this MR requires other branches for the CI pipelines to pass, follow the instructions on this page: https://mujin.atlassian.net/l/cp/sSbxhKP3)
[//]: # (Remember that tests still need to pass after your changes. You may need to submit an MR to the test repository.)
> Updated `detectionPointCloudCorners3D` to a struct containing the corners point in 3D and the 2 corner axes in 3D.

- src/binpickingtaskzmq.cpp
While debugging a timeout problem, I noticed that the exception message changed from its first throw and was lacking information. With this change the message now says it is a timeout exception and what the `taskparameters` where.
> Fill in error code and message for timeout exception

- CMakeLists.txt
The variable `COMPILER_IS_CLANG` is not set anywhere in `CMakeLists.txt` file. Added.
> Add CLANG detection

- include/mujincontrollerclient/mujinjson.h
gcc 12 raises this
```
In file included from /home/mujin/mujin/checkoutroot/controllerclientcpp/include/mujincontrollerclient/mujincontrollerclient.h:60,
from /home/mujin/mujin/checkoutroot/controllerclientcpp/src/common.h:21,
from /home/mujin/mujin/checkoutroot/controllerclientcpp/src/common.cpp:14:
/home/mujin/mujin/checkoutroot/controllerclientcpp/include/mujincontrollerclient/mujinjson.h:557:36: error: redefinition of default argument for ‘class Encoding’
557 | template<typename T, class AllocT, typename Encoding=rapidjson::UTF8<>, typename Allocator=rapidjson::MemoryPoolAllocator<> >
|                                    ^~~~~~~~
/home/mujin/mujin/checkoutroot/controllerclientcpp/include/mujincontrollerclient/mujinjson.h:514:56: note: original definition appeared here
514 | …
```
> Avoid redefinition of template default argument

- src/mujinjson.cpp
`realloc()` may return `NULL`, so when we do:
```
foobar = realloc( foobar );
```
we risk leaking memory, better implementation would be:
```
maybe_good = realloc( foobar )
foobar = maybe_good != NULL ? maybe_good : foobar
....
free( foobar )
```
> Fix leaky realloc()

- include/mujincontrollerclient/mujinjson.h
When using a non-default allocator, the lack of a type-parameterized `SaveJsonValue` for `const *` causes it to select the `bool` specialization instead. 
The reason that the commented out method was ambiguous before is that `const *` and `const T (&t)[N], T = char` are effectively the same. 
Avoid this issue by explicitly disabling that template when T=char so that it uses the `const char*` specialization.
> Fix SaveJsonValue for strings when using non-default allocators

- include/mujincontrollerclient/mujinjson.h
Previous version was _always_ failing to resolve, even for non-char types because is_same does not have a ::type, it has a ::value
This would cause non-char primitive arrays to be serialized as booleans.
> Fix always-failing typename dependency
